version: '3'

services:
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - app-network
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: oikos
      MYSQL_PASSWORD: oikos
      MYSQL_DATABASE: oikos
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - 3306:3306
    volumes:
      - ./database/data/:/var/lib/mysql

networks:
  app-network:
    driver: bridge
