version: '3'

services:
  adminer:
    profiles:
      - "dev"
      - "prod"
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - app-network
  db:
    profiles:
      - "dev"
      - "prod"
    build:
      context: ./database
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: oikos
      MYSQL_PASSWORD: oikos
      MYSQL_DATABASE: oikos
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - 3307:3306
    volumes:
      - ./database/data/:/var/lib/mysql

  dev:
    profiles:
      - "dev"
    container_name: oikos_dev
    image: oikos:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 5000:3000
      - 9229:9229
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  prod:
    profiles:
      - "prod"
    container_name: oikos_prod
    image: oikos-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 5000:3000
      - 9229:9229
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
